Downloads Mirror
MrLetsplay2003/ShittyAuthPatcher pull request #1
Opened 2022-05-02 09:21 UTC by ajh123

This could be useful for people who run a backup for the Mojang servers,
Or if Mojang makes a different place for their experimental snapshots instead of Reddit.

I will make a PR on the launcher, which will allow us to choose the mirrors we want.

Don't know why in the patcher it says I've deleted and replaced the same line?

2022-05-02 09:23 UTC, ajh123 commented
you may also delete my repo from the pom.xml

2022-05-02 12:07 UTC, ajh123 commented
Still needs fixing!

2022-05-02 14:08 UTC, samuelh2005 commented
This is fixed now, just need to publish the launcher fork

2022-05-02 19:20 UTC, ajh123 commented
Still broken!

2022-05-02 19:26 UTC, ajh123 commented
Still :(

2022-05-02 19:31 UTC, ajh123 commented
Saving the mirrors to the launcher config is the problem :(

2022-05-03 19:02 UTC, MrLetsplay2003 commented
I'll probably take a closer look at the changes tomorrow, thank you for your cotribution! :+1:

2022-05-03 19:35 UTC, ajh123 commented
Ok, I've got the config saving now working! I'll publish the launcher changes tomorrow.

2022-05-04 16:04 UTC, MrLetsplay2003 requested changes
IntelliJ changed a lot of the indentation, but overall I think it's fine apart from the things I commented on

2022-05-04 16:04 UTC, MrLetsplay2003 commented on src/me/mrletsplay/shittyauthpatcher/util/LibraryPatcher.java
> +}
This file uses spaces for indentation (probably because one of the methods wrongly used spaces for indentation before), please fix that

2022-05-04 16:04 UTC, MrLetsplay2003 commented on src/me/mrletsplay/shittyauthpatcher/mirrors/DownloadsMirror.java
> +	public String assets_url;
I think these should be renamed to `versionManifest` and `assetsURL` to conform to the Java naming conventions

2022-05-04 16:04 UTC, MrLetsplay2003 commented on pom.xml
> +		<!--</for ajh123>-->
Please remove your local repository before I merge the pull request, otherwise I'll have to make another unnecessary commit

2022-05-05 11:43 UTC, merged